name = "Maudpack"
author = "Coney Poney"
version = "2.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "881a42e336587150e5a7fac0b535859e8bf7fb3dbed7e323617d8936245600ff"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
