name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23f94bd0712a47b35a3a58772014157c1729b2dafb57956769e0f58519e3229a"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.58"
