name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad0c790477c4203ac8cb5c27f29420a2251dd1ab05f0f9a03c955472d651d114"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
