name = "Maudpack"
author = "Coney Poney"
version = "2.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40632a967ba3eb8a67c6b62296904de385856a895f0b0b5b09c34deb10503404"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
