name = "Maudpack"
author = "Coney Poney"
version = "rc-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21f559a7beca168dac0828ed2d4cfc60b31bf71ed6c5add03a44bd5bb5bbbb7a"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
