name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c36f5d8108dd628b2bdd50d25d9cc7807dd911032bb7ae0aa2b28714a491f806"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
