name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d025c1187a3423c46463bd818a695a2c581f10af17fbda6e94ae3400f6f02975"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
