name = "Maudpack"
author = "Coney Poney"
version = "rc-1-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52a43a44161803f6273c9d76fe1156f88a191b5c631dfca4cb9823b2a2e40ca7"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
