name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66c9098cdfe13cec578558d1dbe0e28d79326f0f35231326e460d0e603a46a1e"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
