name = "Maudpack"
author = "Coney Poney"
version = "rc-1-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e9ee9f37de170ba37af23e0073d4d078ff8f708130b1b8e3bb7142a646ec328"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
