name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1089dd1c1db4b6b9a6081585469b21fc69478d21ca01cb54804eea4e28dcf2b1"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
