name = "Maudpack"
author = "Coney Poney"
version = "rc-1-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2daa075be7286d84b559785fd527ecda2a313f198f6e3d3d1f324deebb75d29"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
