name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf21455f069aeb053384554d6afb6c25c6e1ce0fe265b43e1b0bf44f5168b883"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
