name = "Maudpack"
author = "Coney Poney"
version = "2.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89a0ae992e323a576a2a38ee079a199403e86bd2fc68e5bd3a3c6b224c949b78"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
