name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5295483aced3bc8f65c3cc474b34362cd438fc93404fdccadc51eaba3a7ab650"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.58"
