name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09ddc52be1d4072b0d02a6fe24165bda55c7575f9db982c68382bdb6a8a4037d"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
