name = "workingtitle-modpack"
author = "Coney Poney"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77870040b2ed7f5f968f7ff3d75f8f79fdffc714a3959dbc0a7e954765defae1"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.58"
