name = "Maudpack"
author = "Coney Poney"
version = "rc-1-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b38292f2e7fb9383ccb1898947795f3b4860f3c24b590669625677790e9476d"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
