name = "Maudpack"
author = "Coney Poney"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66fc62c98e24507451821e86f0fa3f9d9a52fdcaf5ef7fdb48f51110d1549584"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
