name: Publish .mrpack file
on:
  push:
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Download latest verison of Packwiz
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          repo: packwiz/packwiz
          name: Linux 64-bit x86
          latest: true
          path: ./
      - name: run some diagnostic junk to get an idea of the directory structure
        run: |
          env
          ls -la
      - name: Produce .mrpack
        run: |
          chmod +x ./packwiz
          ./packwiz mr export
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: mrpack
          path: ./*.mrpack
